version: '3.8'

services:
  backend:
    build:
      context: ./src/backend
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    depends_on:
      - backend